"""Update batch

Revision ID: 0088ab4ae091
Revises: 571cbf7ed20b
Create Date: 2025-06-19 13:27:35.156398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0088ab4ae091'
down_revision = '571cbf7ed20b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    # ### end Alembic commands ###
