"""Update Candidate model schema

Revision ID: 290117108a3b
Revises: 5ccd66ffc9cd
Create Date: 2025-06-19 11:43:39.927048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '290117108a3b'
down_revision = '5ccd66ffc9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_column('exam_end_datetime')
        batch_op.drop_column('exam_start_datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_start_datetime', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('exam_end_datetime', mysql.DATETIME(), nullable=False))

    # ### end Alembic commands ###
