"""Update batch

Revision ID: 571cbf7ed20b
Revises: b67f5cdd211d
Create Date: 2025-06-19 13:19:35.375269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571cbf7ed20b'
down_revision = 'b67f5cdd211d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
