"""Update Candidate model schema

Revision ID: 5ccd66ffc9cd
Revises: 837055a27977
Create Date: 2025-06-19 11:33:54.130981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ccd66ffc9cd'
down_revision = '837055a27977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('mobile'))
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_column('gender')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('resume_link')
        batch_op.drop_column('dob')
        batch_op.drop_column('mobile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', mysql.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('dob', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('resume_link', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gender', mysql.ENUM('Male', 'Female', 'Other'), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('mobile'), ['mobile'], unique=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('password')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
