"""Your descriptive message here, e.g., add_admin_table

Revision ID: 837055a27977
Revises: 
Create Date: 2025-06-18 11:33:54.311434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837055a27977'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('python_mcqs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'batches', ['batch_id'], ['batch_id'])
        batch_op.create_foreign_key(None, 'admins', ['created_by'], ['admin_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('python_mcqs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('batch_id')

    # ### end Alembic commands ###
